# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nullify_blanks}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew White"]
  s.date = %q{2009-10-05}
  s.description = %q{Ruby on Rails plugin to ensure nullable databases columns are set to null rather than empty strings.}
  s.email = %q{andyw@pixeltrix.co.uk}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/nullify_blanks.rb",
     "nullify_blanks.gemspec",
     "rails/init.rb",
     "tasks/nullify_blanks_tasks.rake",
     "test/fixtures/products.yml",
     "test/nullify_blanks_test.rb"
  ]
  s.homepage = %q{http://github.com/pixeltrix/nullify_blanks/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Nullify blank columns in ActiveRecord}
  s.test_files = [
    "test/nullify_blanks_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
